apiVersion: v1
kind: Service
metadata:
  name: webpage-nodeport-service-star
  namespace: default
spec:
  selector:
    app: webpage
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort
