apiVersion: v1
kind: Service
metadata:
  name: webpage-nodeport-service-star
  namespace: default
spec:
  clusterIP: 10.43.17.21
  clusterIPs:
    - 10.43.17.21
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: webpage
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
