apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.50.181"],"port":30080,"protocol":"TCP","serviceName":"default:webpage-nodeport-service-star","allNodes":true}]
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/3yQQW/jIBCF/8ucTRbHNiFc976KtFUvVQ8DjBNaBxBMU1WR/3tF0qq33kDz3vfezBUwh0cqNaQIBi49dPAaogcD/6lcgiPo4EyMHhnBXAFjTIwcUqztm+wLOa7EmxLSxiHzQpuQ/oRG2Dmys1JW9KObxOj1JPY76YSV1hEqh73ysHawoKXlV9wJ6wkM7HuPk51nO81K+wH1oHaDHAentlu5Hz2S1L2UukEjngkMvJPNeCQRk6ecCot6X0tUxgJ3Wc3omtbTjG8LN3fN5FqhZqlgnq7QAIdUGMwgpZbdbQTm9iqJk0sLGHj4e4AOGMuR+PAl0HJ97qDSQo5TuR0x559qLY4/civw7ztjXT8DAAD//7hztEGZAQAA
    objectset.rio.cattle.io/id: 7cebf66b-14c5-4d85-970c-b0bcea6ca16d
  creationTimestamp: '2024-04-23T01:30:40Z'
  labels:
    objectset.rio.cattle.io/hash: 91da5bffb5f68d3a83673043c622094dae081008
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/publicEndpoints: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":80,"protocol":"TCP"}:
              .: {}
              f:nodePort: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-04-23T01:30:40Z'
  name: webpage-nodeport-service-star
  namespace: default
  resourceVersion: '1440356'
  uid: 94d76d9f-f3d4-494e-99c3-d69d8899212d
spec:
  clusterIP: 10.43.17.21
  clusterIPs:
    - 10.43.17.21
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: webpage
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

