apiVersion: v1
kind: Service
metadata:
  name: webpage-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 80
    name: http
  selector:
    app: webpage
  externalIPs: 
    - 54.144.9.249
